<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><TargetFramework>net10.0</TargetFramework><LangVersion>14.0</LangVersion><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable><RootNamespace>Commandes.Application</RootNamespace></PropertyGroup>
  <ItemGroup><ProjectReference Include="../TP01_Commandes.Domaine/TP01_Commandes.Domaine.csproj" /></ItemGroup>
</Project>
